[package]
name = "ray_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geom_lib = { path = "../geom_lib" }
draw_lib = { path = "../draw_lib" }
