[package]
name = "draw_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geom_lib = { path = "../geom_lib" }
chrono = "0.4"